name: Build Test Scan

permissions:
  security-events: write
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master

jobs:
  Build-Test-Scan:
    uses: ./.github/workflows/app-reusable-ci.yaml
    
