name: Build Test Scan

on:
  workflow_call:

jobs:
  Build-Test-Scan-Application:

    name: Build Test Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
    
    - name: Test And Compile
      run: mvn clean install
    
    - name: Analyze Vulnerabilities With CodeQL
      uses: github/codeql-action/analyze@v3

    



